credentials:
  usernames:
    gconstant:
      email: gconstant@plouf.com
      name: GaÃ«tan Constant
      password: $2b$12$n9NPjXPmCbb5ah/gzJF.YOHS6NnKcnP14.r/rg.q7g2ccbeT7.fAC # 'scopa' hashed
    admin:
      email: admin@plouf.com
      name: Admin
      password: $2b$12$n9NPjXPmCbb5ah/gzJF.YOHS6NnKcnP14.r/rg.q7g2ccbeT7.fAC # 'scopa' hashed
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails: []
